import React, { useState } from 'react';
import { AuditResult } from '../../types/audit.js';
import { X, Download, Copy, Check, FileCode, FileText } from 'lucide-react';

interface ExportReportModalProps {
  result: AuditResult;
  isOpen: boolean;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  result,
  isOpen,
  onClose,
}) => {
  const [format, setFormat] = useState<'markdown' | 'json'>('markdown');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdownReport = (r: AuditResult): string => {
    let md = `# DocAudit AI — Document Quality & Compliance Report\n\n`;
    md += `**Document:** ${r.documentMeta.fileName} (${r.documentMeta.fileType.toUpperCase()})\n`;
    md += `**Date:** ${new Date(r.analyzedAt).toLocaleString()}\n`;
    md += `**Overall Score:** ${r.overallScore} / 100\n\n`;

    md += `## Executive Summary\n${r.summary}\n\n`;

    md += `## Category Scores\n`;
    md += `- **Spelling & Typos:** ${r.categories.spelling}/100\n`;
    md += `- **Grammar & Syntax:** ${r.categories.grammar}/100\n`;
    md += `- **Sentence Quality:** ${r.categories.sentenceQuality}/100\n`;
    md += `- **Relevance:** ${r.categories.relevance}/100\n`;
    md += `- **Completeness:** ${r.categories.completeness}/100\n`;
    md += `- **Structure & Flow:** ${r.categories.structure}/100\n`;
    md += `- **Assignment Coverage:** ${r.categories.questionCoverage}/100\n\n`;

    if (r.priorityFixes.length > 0) {
      md += `## Priority Fixes\n`;
      r.priorityFixes.forEach((fix, i) => {
        md += `${i + 1}. ${fix}\n`;
      });
      md += `\n`;
    }

    if (r.strengths.length > 0) {
      md += `## Document Strengths\n`;
      r.strengths.forEach((str) => {
        md += `- ${str}\n`;
      });
      md += `\n`;
    }

    if (r.requirements.length > 0) {
      md += `## Assignment Requirements Coverage\n`;
      r.requirements.forEach((req) => {
        md += `### [${req.status.toUpperCase()}] ${req.requirement}\n${req.explanation}\n\n`;
      });
    }

    if (r.issues.length > 0) {
      md += `## Audited Issues (${r.issues.length})\n\n`;
      r.issues.forEach((issue, idx) => {
        md += `### ${idx + 1}. [${issue.severity.toUpperCase()}] ${issue.type} (${issue.confidence}% confidence)\n`;
        if (issue.location) {
          md += `*Location:* Page ${issue.location.pageNumber || 'N/A'}${
            issue.location.paragraph ? `, Para ${issue.location.paragraph}` : ''
          }\n`;
        }
        md += `*Explanation:* ${issue.explanation}\n`;
        if (issue.originalText) {
          md += `*Original:* \`${issue.originalText}\`\n`;
        }
        if (issue.suggestion) {
          md += `*Suggestion:* \`${issue.suggestion}\`\n`;
        }
        md += `\n`;
      });
    }

    md += `---\n*Generated by DocAudit AI*`;
    return md;
  };

  const exportContent =
    format === 'markdown'
      ? generateMarkdownReport(result)
      : JSON.stringify(result, null, 2);

  const handleCopy = () => {
    navigator.clipboard.writeText(exportContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([exportContent], {
      type: format === 'markdown' ? 'text/markdown' : 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `DocAudit-${result.documentMeta.fileName.replace(/\.[^/.]+$/, '')}.${
      format === 'markdown' ? 'md' : 'json'
    }`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-150">
      <div className="relative w-full max-w-3xl max-h-[85vh] flex flex-col rounded-3xl bg-[#141417] shadow-2xl border border-white/10 overflow-hidden">
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-[#0F0F11]">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
              <Download className="h-5 w-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">Export Audit Report</h3>
              <p className="text-xs text-slate-400">Download or copy your complete document audit findings.</p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="rounded-xl p-2 text-slate-400 hover:bg-white/10 hover:text-white transition-colors cursor-pointer"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Format Selector Bar */}
        <div className="flex items-center justify-between px-6 py-3 border-b border-white/5 bg-[#141417]">
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => setFormat('markdown')}
              className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-semibold transition-colors cursor-pointer ${
                format === 'markdown'
                  ? 'bg-indigo-600 text-white'
                  : 'bg-white/5 text-slate-300 hover:bg-white/10 border border-white/5'
              }`}
            >
              <FileText className="h-3.5 w-3.5" /> Markdown (.md)
            </button>
            <button
              type="button"
              onClick={() => setFormat('json')}
              className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-semibold transition-colors cursor-pointer ${
                format === 'json'
                  ? 'bg-indigo-600 text-white'
                  : 'bg-white/5 text-slate-300 hover:bg-white/10 border border-white/5'
              }`}
            >
              <FileCode className="h-3.5 w-3.5" /> Structured JSON (.json)
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-semibold text-slate-300 hover:bg-white/10 hover:text-white transition-colors cursor-pointer"
            >
              {copied ? (
                <>
                  <Check className="h-3.5 w-3.5 text-emerald-400" />
                  <span className="text-emerald-400">Copied</span>
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5" />
                  <span>Copy</span>
                </>
              )}
            </button>
            <button
              type="button"
              onClick={handleDownload}
              className="inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3.5 py-1.5 text-xs font-semibold text-white shadow-[0_0_20px_rgba(79,70,229,0.3)] hover:bg-indigo-500 transition-colors cursor-pointer"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

        {/* Code / Text Preview */}
        <div className="flex-1 overflow-y-auto p-6 bg-[#0A0A0B] text-slate-300 font-mono text-xs leading-relaxed whitespace-pre-wrap selection:bg-indigo-900/60 selection:text-indigo-200">
          {exportContent}
        </div>
      </div>
    </div>
  );
};
